server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Todas las rutas van al index.html para soportar el router de React
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuración opcional para caché de archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000";
    }
}
